### ISSUE TITLE
Categorise the "outputTransforms" by display types.

### ISSUE THREAD

**Issue by KelSolaar** [ampas/aces-dev#120]
Hi,

To help the automatic discovery of the *CTL* transforms and for consistency purposes it would be great to have the *outputTransforms* categorised by display types like for the ODTs:

![image](https://user-images.githubusercontent.com/99779/86710729-62d12d00-c06f-11ea-814a-304a46be87c1.png)

Cheers,

Thomas

**Comment by KelSolaar** [comment]
Hello!

Any chance to get #121 merged please @scottdyer?

```yaml
displays:
  DCDM:
    - !<View> {name: DCDM, colorspace: Output - DCDM}
    - !<View> {name: DCDM P3D60, colorspace: Output - DCDM P3D60}
    - !<View> {name: DCDM P3D65limited, colorspace: Output - DCDM P3D65limited}
  P3:
    - !<View> {name: P3D60 48nits, colorspace: Output - P3D60 48nits}
    - !<View> {name: P3D65 48nits, colorspace: Output - P3D65 48nits}
    - !<View> {name: P3D65 709limit 48nits, colorspace: Output - P3D65 709limit 48nits}
    - !<View> {name: P3D65 D60sim 48nits, colorspace: Output - P3D65 D60sim 48nits}
    - !<View> {name: P3DCI 48nits, colorspace: Output - P3DCI 48nits}
    - !<View> {name: P3DCI D65sim 48nits, colorspace: Output - P3DCI D65sim 48nits}
  Rec. 2020:
    - !<View> {name: Rec2020, colorspace: Output - Rec2020 100nits dim}
    - !<View> {name: Rec2020 100nits, colorspace: Output - Rec2020 100nits}
    - !<View> {name: Rec2020 Rec709limited 100nits, colorspace: Output - Rec2020 Rec709limited 100nits}
  Rec. 709:
    - !<View> {name: Rec709, colorspace: Output - Rec709 100nits dim}
    - !<View> {name: Rec709 D60sim, colorspace: Output - Rec709 D60sim 100nits dim}
  sRGB:
    - !<View> {name: sRGB, colorspace: Output - sRGB 100nits dim}
    - !<View> {name: sRGB D60sim, colorspace: Output - sRGB D60sim 100nits dim}
  undefined:
    - !<View> {name: P3D65 1000nits 15nits ST2084, colorspace: Output - P3D65 1000nits 15nits ST2084}
    - !<View> {name: P3D65 108nits 7nits ST2084, colorspace: Output - P3D65 108nits 7nits ST2084}
    - !<View> {name: P3D65 2000nits 15nits ST2084, colorspace: Output - P3D65 2000nits 15nits ST2084}
    - !<View> {name: P3D65 4000nits 15nits ST2084, colorspace: Output - P3D65 4000nits 15nits ST2084}
    - !<View> {name: Rec2020 1000nits 15nits HLG, colorspace: Output - Rec2020 1000nits 15nits HLG}
    - !<View> {name: Rec2020 1000nits 15nits ST2084, colorspace: Output - Rec2020 1000nits 15nits ST2084}
    - !<View> {name: Rec2020 2000nits 15nits ST2084, colorspace: Output - Rec2020 2000nits 15nits ST2084}
    - !<View> {name: Rec2020 4000nits 15nits ST2084, colorspace: Output - Rec2020 4000nits 15nits ST2084}

```
