### ISSUE TITLE
Some CTL transform files are missing descriptions.

### ISSUE THREAD

**Issue by KelSolaar** [ampas/aces-dev#123]
While for example, https://github.com/ampas/aces-dev/blob/master/transforms/ctl/csc/ACEScc/ACEScsc.Academy.ACES_to_ACEScc.ctl has a very good description that I can extract to build the OCIO config, https://github.com/ampas/aces-dev/blob/master/transforms/ctl/csc/arri/ACEScsc.Academy.ACES_to_LogC_EI800_AWG.ctl does not have.

```yaml
  - !<ColorSpace>
    name: ACES - ACEScc
    family: ACES
    equalitygroup: ""
    bitdepth: 32f
    description: |
      ACES Color Space Conversion - ACEScc to ACES
      
      converts ACEScc (AP1 w/ ACESlog encoding) to
      ACES2065-1 (AP0 w/ linear encoding)
      
      This transform follows the formulas from section 4.4 in S-2014-003
      
      *-*-*-*-*-*-*-*-*
      ACEScc is intended to be transient and internal to software or hardware
      systems, and is specifically not intended for interchange or archiving.
      ACEScc should NOT be written into a container file in actual implementations!
      *-*-*-*-*-*-*-*-*
    isdata: false
    allocation: uniform

  - !<ColorSpace>
    name: ACES - LogC_EI800_AWG
    family: ACES
    equalitygroup: ""
    bitdepth: 32f
    isdata: false
    allocation: uniform
```

Please don't pay attention to the allocation or anything besides the description in the above YAML snippet.
